### ISSUE TITLE
Broken after Windows update 4-29-2018

### ISSUE THREAD

**Issue by PastaJ** [basildane/WakeOnLAN#102]
WOL errors out after the newest Windows features update automatically installed on 29 April 2018 (is 10 BOD in a row now considered a feature?).

I've uninstalled and reinstalled WOL twice, but that does not fix the problem.

**Here's the output from WOL:**
at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at WakeOnLan.My.MySettings.get_TraceLog()
   at WakeOnLan.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by basildane** [comment]
Hi, I am running 1803 update on Windows 10 Pro here, I cannot duplicate the problem.
What is WOL2?
Can you describe what you are doing with the VPN and what is happening?

**Comment by Dryoyolino** [comment]
Hy basildane,
please Google "WOL2" you will find 1st. page of developer and 2nd:
"The Wake On Lan Tool 2 is the successor of the Wake On Lan Tool Classic. The Wake On Lan Tool 2 is a complete rewrite of the successful classic version with …"
When I use WOL from Aquila Technology AND I do not use a VPN-Conection to my Company server, all is working same as before Windows April /Spring update 1803.
When I connet to my Company Server with VPN, the WOL stops working and crushes every time.
Even with latest official patch to Build (17134.48) WOL is not working anymore.
Because of that, now I am usind WOL2 that works with VPN conections. Sorry for so lang explanations, I think I am repeating almost anything.
Regards from Germany.

**Comment by basildane** [comment]
If the program crashes, does it give an error message?
Even if it doesn't, it should write a log file if it crashes.

The file can be found here: C:\Users\[YourUserName]\AppData\Roaming\Aquila Technology\WakeOnLan\[VersionNumber]\WakeOnLan.log

For example: C:\Users\phil\AppData\Roaming\Aquila Technology\WakeOnLan\2.7.5.1\WakeOnLan.log

Could you please send me that file?
You can upload to me [here](https://cloud.aquilatech.com/s/cKHVPHPXfaYdbjn)
