### ISSUE TITLE
WakeOnLAN crashes when EventLog is opened

### ISSUE THREAD

**Issue by jdg45** [basildane/WakeOnLAN#201]
Hi, 
Latest version 2.12.4
The program locks up and when stopped [crashed by stop program] produces a Windows error.
WOL History has (Not Responding) at the top of the log page and no data.
 X to close the program sometimes gives a crash report. I gather I log file is be locked?

It seems that the log file is NOT produced. No idea why it is not created.

Suggestions how to get a readable log file would be appreciated.

OK. I shut down WOL program from the taskbar[hidden] and then the log file was readable.
It was locked by its own program!!

**WHY cannot WOL display its own log file???**

Thanks
JDG

An unexpected exception occurred.
Error message
The process cannot access the file 'C:\users\library\documents\wakeonlan.tracelog' because it is in use by another process.

  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at WakeOnLan.Tracelog.Load()
   at WakeOnLan.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by basildane** [comment]
There are two different "logs" here.  The Event Log is real-time log of what the system is doing, this uses the windows event log.  You can view this with windows or with WOL using the event log button.

The second is the "trace log", which sounds like what you are asking about.  The trace log is a low-level debugging log that was intended to be used in an emergency when there is a serious fault and you need help trying to diagnose the problem.  It is not intended to by used in normal operations, and it cannot be read while the program is running.  It is strictly for debugging by software developers.  Once you close the program, the trace is closed and you can read it or upload to me for help.

Hope this helps.

**Comment by jdg45** [comment]
Thanks. On the menu View / Event Log was the locking up problem. But not
immediately.
Seems OK now but the response time (on an older processor) is slowww.
Regards,
j
